name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest

    if: "!startsWith(github.event.head_commit.message, '(chore:version)')"

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Increment version
        run: |
          git config --global user.name 'version-boy'
          git config --global user.email 'charlie@thmsn.dev'
          npm version patch -m "(chore:version) %s"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
